// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: [
        'intro',
        'preface',
        'appendix',
      ],
    },
    {
      type: 'category',
      label: 'Foundations',
      items: [
        {
          type: 'autogenerated',
          dirName: 'foundations',
        },
      ],
    },
    {
      type: 'category',
      label: 'Electronics',
      items: [
        {
          type: 'autogenerated',
          dirName: 'electronics',
        },
      ],
    },
    {
      type: 'category',
      label: 'Mechanics',
      items: [
        {
          type: 'autogenerated',
          dirName: 'mechanics',
        },
      ],
    },
    {
      type: 'category',
      label: 'Simulation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'simulation',
        },
      ],
    },
    {
      type: 'category',
      label: 'ROS2',
      items: [
        {
          type: 'autogenerated',
          dirName: 'ros2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Isaac',
      items: [
        {
          type: 'autogenerated',
          dirName: 'isaac',
        },
      ],
    },
    {
      type: 'category',
      label: 'AI Brain',
      items: [
        {
          type: 'autogenerated',
          dirName: 'ai-brain',
        },
      ],
    },
    {
      type: 'category',
      label: 'VLA',
      items: [
        {
          type: 'autogenerated',
          dirName: 'vla',
        },
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-1',
        },
        {
          type: 'autogenerated',
          dirName: 'module-2',
        },
        {
          type: 'autogenerated',
          dirName: 'module-3',
        },
        {
          type: 'autogenerated',
          dirName: 'module-4',
        },
      ],
    },
    {
      type: 'category',
      label: 'Capstone',
      items: [
        {
          type: 'autogenerated',
          dirName: 'capstone',
        },
      ],
    },
  ],
};

module.exports = sidebars;